[client]
showErrorDetails = false
toolbarMode = "viewer"

[logger]
level = "error"

[server]
headless = true
port = 8501
runOnSave = true

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"
